service: my-airsofia-check

provider:
  name: aws
  profile: serverless-cli
  runtime: nodejs8.10
  region: eu-west-1

  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

package:
  include:
    - handler.js
    - lib/**
    - node_modules/**

functions:
  check:
    handler: handler.check
    events:
      - http:
          path: check
          method: get
      - schedule: rate(10 minutes)
   

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
