service: my-airsofia-check

provider:
  name: aws
  profile: serverless-cli
  runtime: nodejs8.10
  region: eu-west-1

  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${self:provider.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        # - "Fn::GetAtt": [ CheckTable, Arn ] #  long YAML form
        - !GetAtt CheckTable.Arn   #  short YAML form
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: ["*"]

package:
  # excludeDevDependencies: true  # this already true by default
  exclude:
    - __tests__/**
    - .vscode/**
    - mock/**
    - .editorconfig
    - .eslintrc
    - env.yml
    - package-lock.json
    - package.json

functions:
  check:
    handler: handler.check
    events:
      # - http:
      #     path: check
      #     method: get
      # - schedule: rate(10 minutes)
      # - schedule: rate(1 hour)
      #           cron(Minutes Hours Day-of-month Month Day-of-week Year)
      - schedule: cron(0/30 7-20 ? * * *) # Run every 30 minutes between 7:00am and 7:30pm (UTC) every day
      # - schedule: cron(0/30 7-20 ? * MON-FRI *) # Run every30 minutes between 7:00am and 7:30pm (UTC) Mon-Fri
    environment:
      # Ref of a DynamoDB Table returns its name
      # AWS_DYNAMODB_CHECK: { Ref: CheckTable }  #  long YAML form
      AWS_DYNAMODB_CHECK: !Ref CheckTable #  short YAML form
          
   
resources:
  Resources:
    CheckTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
